version: '3.4'

services:
  urlshortener:
    image: urlshortener
    build:
      context: .
      dockerfile: UrlShortener/Dockerfile
    environment:
      - "ConnectionStrings__DefaultConnection=Server=db;Database=UrlShortenerDB;User=sa;Password=Password123;MultipleActiveResultSets=true;"
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5001:80"
    depends_on:
      - db
    restart: on-failure

  db:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    environment:
      MSSQL_SA_PASSWORD: 'Password123'
      ACCEPT_EULA: 'Y'